---
- name: checkout dotfiles
  git:
    repo: https://github.com/plmi/dotfiles.git
    dest: "{{ dotfiles.dest }}"
    force: true

- name: install dotfiles
  command: make
  args:
    chdir: "{{ dotfiles.dest }}"

- name: create xsession directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /usr/share/xsessions
    state: directory
    mode: '0755'

- name: add dwm shortcut
  become: true
  ansible.builtin.copy:
    src: "{{ dotfiles.dest }}/dwm.desktop"
    dest: /usr/share/xsessions/dwm.desktop
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: change default shell of {{ username }}
  become: yes
  user:
    name: "{{ username }}"
    shell: "{{ shell }}"

- include_tasks: bat.yml