common:
  pacman:
    - alsa-utils
    - aria2
    - bat
    - browserpass
    - browserpass-chromium
    - chromium
    - dhcpcd
    - dunst
    - emacs
    - eza
    - feh
    - flameshot
    - freerdp
    - fzf
    - git
    - inetutils
    - inotify-tools
    - iperf3
    - less
    - maim
    - mpv
    - neofetch
    - neovim
    - net-tools
    - netctl
    - nfs-utils
    - okular
    - openssh
    - openvpn
    - p7zip
    - pacman-contrib
    - pass
    - redshift
    - ripgrep
    - speedtest-cli
    - stow
    - sxiv
    - thunderbird
    - tmux
    - unzip
    - vim
    - wget
    - xclip
    - xdotool
    - xorg-server
    - xorg-xev
    - xorg-xinit
    - xorg-xrandr
    - xorg-xsetroot
    - xorg-xwininfo
    - xwallpaper
    - yt-dlp
    - zathura
    - zathura-pdf-mupdf
    - zip
    - zoxide
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting

yay:
  dest: "/tmp/yay"
  dependencies:
    - git
    - base-devel
  packages:
    - visual-studio-code-bin
    - nvm

man:
  pacman:
    - man-pages
    - man-db

fonts:
  pacman:
    - ttf-iosevka-nerd
    - ttf-jetbrains-mono-nerd

printer:
  pacman:
    - cups
    - avahi
    - hplip

university:
  pacman:
    - gimp
    - textlive-most
    - texlive-binextra

blackarch:
  pacman:
    - nmap
    - burpsuite
    - metasploit
  strap_sh_url: https://blackarch.org/strap.sh
  strap_sh_path: /tmp/strap.sh

dwm:
  repo: https://github.com/bakkeby/dwm-flexipatch.git
  dest: "/home/{{ username }}/.local/src/dwm"
  temp_dest: "/home/{{ username }}/.local/src/dwm.tmp"
  patches:
    - CENTER_PATCH
    - BAR_STATUSCOLORS_PATCH
    - FAKEFULLSCREEN_PATCH
    - PERTAG_PATCH
    - RENAMED_SCRATCHPADS_PATCH
  diffs:
    - base.config.diff
    - statuscolors.config.diff

flexipatch_finalizer:
  repo: https://github.com/bakkeby/flexipatch-finalizer.git
  dest: "/home/{{ username }}/.local/src/flexipatch-finalizer"

st:
  repo: https://github.com/bakkeby/st-flexipatch.git
  luke_repo: https://github.com/LukeSmithxyz/st.git
  luke_build_dest: /tmp/st
  build_dest: "/home/{{ username }}/.local/src/st.tmp"
  dest: "/home/{{ username }}/.local/src/st"
  patches:
    - ALPHA_PATCH
    - ALPHA_FOCUS_HIGHLIGHT_PATCH
    - BOLD_IS_NOT_BRIGHT_PATCH
    - CLIPBOARD_PATCH
    - EXTERNALPIPE_PATCH
    - SCROLLBACK_PATCH
    - SCROLLBACK_MOUSE_ALTSCREEN_PATCH
    - XRESOURCES_PATCH
  binaries:
    - st-copyout
    - st-urlhandler
  diffs:
    - theme.config.diff
    - st-commands.config.diff

dmenu:
  repo: https://github.com/bakkeby/dmenu-flexipatch.git
  build_dest: "/home/{{ username }}/.local/src/dmenu.tmp"
  dest: "/home/{{ username }}/.local/src/dmenu"
  patches:
    - BORDER_PATCH
    - CENTER_PATCH
    - FUZZYMATCH_PATCH
    - GRID_PATCH
    - INSTANT_PATCH
    - HIGHPRIORITY_PATCH
    - XRESOURCES_PATCH
  diffs:
    - dmenu.config.diff

dwmblocks:
  repository: https://github.com/UtkarshVerma/dwmblocks-async.git
  dest: "/home/{{ username }}/.local/src/dwmblocks-async"
  blocks:
    dest: "/usr/local/bin/"
    glob1: "/home/{{ username }}/dotfiles/x11/bin/sb-*"
  diffs:
    - dwmblocks.config.diff

tabbed:
  repository: https://github.com/bakkeby/tabbed-flexipatch.git
  dest: "/home/{{ username }}/.local/src/tabbed"
  build_dest: "/tmp/tabbed"
  patches:
    - BAR_HEIGHT_PATCH
    - XRESOURCES_PATCH
  diffs:
    - ''

entr:
  repository: https://github.com/eradman/entr.git
  dest: "/home/{{ username }}/.local/src/entr"

docker:
  group: docker
  packages:
  - docker
  - docker-compose

network:
  name: lan
  cidr: 192.168.8.0/24
  gateway: 192.168.8.1
  ip: 192.168.8.102
  interface: ens18
  dns1: 1.1.1.1
  dns2: 8.8.8.8

ssh:
  hosts:
    - hostname: artemis
      ip: 192.168.8.114
    - hostname: demeter
      ip: 192.168.8.118
    - hostname: gaia
      ip: 192.168.8.101

anki:
  script: download-anki.sh
  script_dest: "/home/{{ username }}/.local/src"
  dest: "/home/{{ username }}/.local/src/anki"
  dependencies:
    - libxcb
    - xcb-util-wm
    - xcb-util-keysyms
    - xcb-util-renderutil
    - qt6-base

pyenv:
  repo: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
  dest: "/home/{{ username }}/.pyenv"
  dependencies: 
    - base-devel
    - openssl
    - zlib
    - xz
    - tk

bat:
  temp_dest: /tmp/bat

grub:
  config: /etc/default/grub

dotfiles:
  repo: https://github.com/plmi/dotfiles.git
  dest: "/home/{{ username }}/dotfiles"

username: michael
timezone: Europe/Berlin
shell: /usr/bin/zsh
public_key_name: "homeserver"
