---
- name: download strap.sh script
  get_url:
    url: "{{ blackarch.strap_sh_url }}"
    dest: "{{ blackarch.strap_sh_path }}"

- name: set execute permissions
  file:
    path: "{{ blackarch.strap_sh_path }}"
    mode: '+x'

- name: execute strap.sh script
  become: true
  command: "{{ blackarch.strap_sh_path }}"
