---
- name: download strap.sh script
  get_url:
    url: {{ strap_sh_url }}
    dest: {{ strap_sh_path }}
  register: strap_sh

- name: set execute permissions
  file:
    path: {{ strap_sh_path }}
    mode: '+x'
  when: download_result.status == 'success'

- name: execute strap.sh script
  command: "{{ strap_sh_path }}"
