---
- name: check if dotfiles exists
  ansible.builtin.stat:
    path: "{{ dotfiles_directory }}"
  register: dotfiles_stat

- name: checkout dotfiles
  git:
    repo: https://github.com/plmi/dotfiles.git
    dest: "{{ dotfiles_directory }}"
  when: not dotfiles_stat.stat.exists
  register: git_checkout_result
