---
- name: delete directories
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ dwm.temp_dest }}"
    - "{{ dwm.dest }}"

- name: create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ dwm.temp_dest }}"
    state: directory
    mode: '0755'

- name: checkout dwm
  git:
    repo: "{{ dwm.repo }}"
    dest: "{{ dwm.temp_dest }}"

- name: add patches
  command: sed -i "s/{{ item }} 0/{{ item }} 1/" {{ dwm.temp_dest }}/patches.def.h
  with_items: "{{ dwm.patches }}"

# https://github.com/bakkeby/dwm-flexipatch/issues/72
- name: update config.mk if swallow patch enabled
  command: sed -i '/XCBLIBS/s/^#//g' {{ dwm.temp_dest }}/config.mk
  when: "'SWALLOW_PATCH' in {{ dwm.patches }}"

- name: compile dwm
  command: make
  args:
    chdir: "{{ dwm.temp_dest }}"

- name: checkout flexipatch-finalizer
  git:
    repo: "{{ flexipatch_finalizer.repo }}"
    dest: "{{ flexipatch_finalizer.dest }}"

- name: finalize dwm
  command: "./flexipatch-finalizer.sh -r -d {{ dwm.temp_dest }} -o {{ dwm.dest }}"
  args:
    chdir: "{{ flexipatch_finalizer.dest }}"

- name: apply diff files
  patch:
    src: "{{ item }}"
    basedir: "{{ dwm.dest }}"
    strip: 1
  with_items: "{{ dwm.diffs }}"

- name: install dwm
  become: true
  command: make clean install
  args:
    chdir: "{{ dwm.dest }}"

- name: delete dwm temp directory
  ansible.builtin.file:
    state: absent
    path: "{{ dwm.temp_dest }}"