---
- include_tasks: timezone.yml
- include_tasks: user.yml
- include_tasks: grub.yml
  args:
    apply:
      become: yes
- include_tasks: man.yml
  args:
    apply:
      become: yes
- include_tasks: pacman.yml
  args:
    apply:
      become: yes
- include_tasks: yay.yml
- include_tasks: fonts.yml
- include_tasks: pyenv.yml
- include_tasks: st.yml
- include_tasks: dwm.yml
- include_tasks: dwmblocks.yml
- include_tasks: tabbed.yml
- include_tasks: dmenu.yml
- include_tasks: entr.yml
- include_tasks: docker.yml
  args:
    apply:
      become: yes
