---
- include_tasks: timezone.yml
- include_tasks: grub.yml
- include_tasks: pacman.yml
  args:
    apply:
      become: yes
- include_tasks: yay.yml
- include_tasks: pyenv.yml
- include_tasks: st.yml
- include_tasks: dwm.yml
- include_tasks: docker.yml
