---
- name: Update and upgrade existing packages
  pacman:
    update_cache: true
    upgrade: true

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install packages
  pacman:
    name: "{{ common_packages }}"
    state: present
