---
- name: check if pyenv exists
  ansible.builtin.stat:
    path: "{{ pyenv.dest }}"
  register: pyenv_directory

- name: install pyenv build dependencies
  become: true
  pacman:
    name: "{{ pyenv.dependencies }}"
    state: present
  when: not pyenv_directory.stat.exists

- name: install pyenv
  shell: curl -L {{ pyenv.repo }} | bash
  when: not pyenv_directory.stat.exists
