---
- name: check if pyenv exists
  ansible.builtin.stat:
    path: "{{ pyenv_directory }}"
  register: pyenv_directory

- name: install pyenv build dependencies
  become: true
  pacman:
    name: "{{ pyenv_dependencies }}"
    state: present
  when: not pyenv_directory.stat.exists

- name: install pyenv
  shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  when: not pyenv_directory.stat.exists
