---
- name: install anki build dependencies
  become: true
  pacman:
    name: "{{ anki.dependencies }}"
    state: present

- name: copy download script
  copy:
    src: "{{ anki.script }}"
    dest: "{{ anki.script_dest }}"
    mode: '0755'

- name: execute download script
  shell: "{{ anki.script_dest }}/{{ anki.script }}"

- name: execute download script
  become: true
  shell: "{{ anki.dest }}/install.sh"
  args:
    chdir: "{{ anki.dest }}/"
